### ISSUE TITLE
package install curl not installing curl

### ISSUE THREAD

**Issue by aaronpederson** [colstrom/package.sh#3]
RUN package install curl
`root@da29fcfe4e22:/# package install curl
root@da29fcfe4e22:/# curl
bash: curl: command not found
root@da29fcfe4e22:/# apt-get install curl
Reading package lists... Done`

**Comment by colstrom** [comment]
What's your Dockerfile look like (up to the point this `RUN` is called)?

**Comment by aaronpederson** [comment]
FROM aaronpederson/ubuntu
MAINTAINER aaron.pederson@gmail.com

RUN package install curl

RUN ansible-galaxy install aaronpederson.ansible-php7
COPY playbook.yml /etc/
RUN ansible-playbook /etc/playbook.yml

**Comment by colstrom** [comment]
Bug seems to be in the `missing` function. `dpkg-query --show` is not a reliable detection method.
